### ISSUE TITLE
Sudo needed to run and keyboard shortcuts not working on Wayland session

### ISSUE THREAD

**Issue by ItzcoR** [lrq3000/pyugt#10]
I installed using miniconda and seems like the keyboard python module needs root access or to be installed as root, see https://stackoverflow.com/questions/48796147/import-error-you-must-be-root. Conda makes it more difficult to add packages as root.  Tried activating the venv and reinstalling the package as root to no avail, still can get around the issue by running pyugt as root. This is the error: 

pyugt - Python Universal Game Translator v1.0.10 - started
Languages available for OCR: []
Traceback (most recent call last):
  File "/home/itzco/Documents/miniconda3/bin/pyugt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/pyugt/pyugt.py", line 682, in main
    keyboard.add_hotkey(config['USER']['hotkey_set_region_capture'], selectRegion, args=(sct, RegionSelector, config, config_internal))  # Do NOT set suppress=True, else this may raise exceptions!
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/__init__.py", line 639, in add_hotkey
    _listener.start_if_necessary()
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.

The second issue I have is when running on KDE plasma with a Wayland session the keyboard shortcuts don't work throwing the following errors on the console 

Hit ctrl+shift+F3 to set the region to capture.
Hit ctrl+F3 to translate the region (make sure to close the translation window before requesting another one).
Hit ctrl+F2 to set AND translate a region.
Hit ctrl+p to show/hide OCR preview.
Press CTRL+C or close this window to quit.
Exception in thread Thread-18 (process):
Traceback (most recent call last):
  File "/home/itzco/Documents/miniconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/itzco/Documents/miniconda3/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/_generic.py", line 58, in process
    if self.pre_process_event(event):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/__init__.py", line 218, in pre_process_event
    callback(event)
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/__init__.py", line 649, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logically_pressed_keys) or (event_type == e.event_type and callback())
                                                                                                                                                          ^^^^^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/keyboard/__init__.py", line 637, in <lambda>
    callback = lambda callback=callback: callback(*args)
                                         ^^^^^^^^^^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/pyugt/pyugt.py", line 238, in selectRegion
    sct_img = sct2.grab(sct2.monitors[monitor]) if monitor >= 0 else 1 # sct.shot() captures the first monitor, sct.shot(mon=-1) captures all monitors, but they cannot capture a specific region. Under the hood, sct.shot() uses sct.save(), which itself calls sct.grab(), itself calling PIL.ImageGrab.grab(), with sct.grab(1) capturing the first monitor (it's 1-indexed, not 0! sct.monitors[0] should contain the list of all monitors), etc. - note that only sct.shot() can capture automatically the first monitor or all monitors, not grab() which on the other hand can capture a specific region on screen if provided a bounding box
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/mss/base.py", line 101, in grab
    screenshot = self._grab_impl(monitor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/mss/linux.py", line 428, in _grab_impl
    ximage = self.xlib.XGetImage(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/mss/linux.py", line 230, in _validate
    raise ScreenShotError(msg, details=details)
mss.exception.ScreenShotError: XGetImage() failed
^CTraceback (most recent call last):
  File "/home/itzco/Documents/miniconda3/bin/pyugt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/itzco/Documents/miniconda3/lib/python3.12/site-packages/pyugt/pyugt.py", line 694, in main
    time.sleep(1)
KeyboardInterrupt

keyboard shortcuts work under a x11 session

**Comment by lrq3000** [comment]
Thank you very much for your feedback! I will add in the readme that it is necessary to run the app with elevated permissions on Linux because of the keyboard shortcuts. I thought this was a userspace permission but it's not given the error you are reporting.

Le 15 décembre 2024 05:13:47 GMT+01:00, ItzcoR ***@***.***> a écrit :
