### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shikulja** [lrq3000/pyugt#2]
C:\Users\User>pyugt
pyugt - Python Universal Game Translator v0.5.3 - started
Languages available for OCR: ['afr', 'amh', 'ara', 'asm', 'aze', 'aze_cyrl', 'bel', 'ben', 'bod', 'b
os', 'bre', 'bul', 'cat', 'ceb', 'ces', 'chi_sim', 'chi_sim_vert', 'chi_tra', 'chi_tra_vert', 'chr',
 'cos', 'cym', 'dan', 'deu', 'div', 'dzo', 'ell', 'eng', 'enm', 'epo', 'equ', 'est', 'eus', 'fao', '
fas', 'fil', 'fin', 'fra', 'frk', 'frm', 'fry', 'gla', 'gle', 'glg', 'grc', 'guj', 'hat', 'heb', 'hi
n', 'hrv', 'hun', 'hye', 'iku', 'ind', 'isl', 'ita', 'ita_old', 'jav', 'jpn', 'jpn_vert', 'kan', 'ka
t', 'kat_old', 'kaz', 'khm', 'kir', 'kmr', 'kor', 'lao', 'lat', 'lav', 'lit', 'ltz', 'mal', 'mar', '
mkd', 'mlt', 'mon', 'mri', 'msa', 'mya', 'nep', 'nld', 'nor', 'oci', 'ori', 'osd', 'pan', 'pol', 'po
r', 'pus', 'que', 'ron', 'rus', 'san', 'sin', 'slk', 'slv', 'snd', 'spa', 'spa_old', 'sqi', 'srp', '
srp_latn', 'sun', 'swa', 'swe', 'syr', 'tam', 'tat', 'tel', 'tgk', 'tha', 'tir', 'ton', 'tur', 'uig'
, 'ukr', 'urd', 'uzb', 'uzb_cyrl', 'vie', 'yid', 'yor']
Hit ctrl+shift+F3 to set the region to capture.
Hit ctrl+F3 to translate the region (make sure to close the translation window before requesting ano
ther one).
Hit ctrl+F2 to set AND translate a region.
Press CTRL+C or close this window to quit.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\threading.py", line 954, in _bootst
rap_inner
    self.run()
  File "c:\users\user\appdata\local\programs\python\python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\keyboard\_generic.py"
, line 58, in process
    if self.pre_process_event(event):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\keyboard\__init__.py"
, line 218, in pre_process_event
    callback(event)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\keyboard\__init__.py"
, line 649, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logic
ally_pressed_keys) or (event_type == e.event_type and callback())
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\keyboard\__init__.py"
, line 637, in <lambda>
    callback = lambda callback=callback: callback(*args)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pyugt\pyugt.py", line
 433, in translateRegion
    transtext = gtranslate(ocrtext, langsource_trans, langtarget)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\pyugt\pyugt.py", line
 350, in gtranslate
    transobj = translator.translate(ocrtext, src=langsource_trans, dest=langtarget)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\googletrans\client.py
", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\googletrans\client.py
", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\googletrans\gtoken.py
", line 194, in do
    self._update()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\googletrans\gtoken.py
", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by DzL0rd** [comment]
After a whole afternoon of searching, I found the solution on a [forum](https://stackoverflow.com/questions/52455774/googletrans-stopped-working-with-error-nonetype-object-has-no-attribute-group), it is a problem with the outdated **"googletrans"**.
Well, it worked for me.

With the anaconda console open, type:

 `pip install googletrans == 4.0.0-rc1`

Give me feedback if it worked or not
