### ISSUE TITLE
Error trying to translate text

### ISSUE THREAD

**Issue by kavikthewolfdog** [lrq3000/pyugt#4]
After selecting a region and trying to translate it, I get this error:

pyugt - Python Universal Game Translator v0.5.2 - started
Languages available for OCR: ['eng', 'jpn', 'jpn_vert', 'osd']
Hit ctrl+shift to set the region to capture.
Hit shift+x to translate the region (make sure to close the translation window before requesting another one).
Hit ctrl+x to set AND translate a region.
Press CTRL+C or close this window to quit.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\keyboard\_generic.py", line 58, in process
  File "site-packages\keyboard\__init__.py", line 218, in pre_process_event
  File "site-packages\keyboard\__init__.py", line 649, in <lambda>
  File "site-packages\keyboard\__init__.py", line 637, in <lambda>
  File "pyugt\pyugt.py", line 444, in selectAndTranslateRegion
  File "pyugt\pyugt.py", line 420, in translateRegion
  File "pyugt\pyugt.py", line 337, in gtranslate
  File "site-packages\googletrans\client.py", line 172, in translate
  File "site-packages\googletrans\client.py", line 75, in _translate
  File "site-packages\googletrans\gtoken.py", line 200, in do
  File "site-packages\googletrans\gtoken.py", line 65, in _update
AttributeError: 'NoneType' object has no attribute 'group'

I saw on a similar thread that running this command in anaconda console fixed the issue: pip install googletrans==4.0.0rc1 
But after installing that I still get the same error.

**Comment by lrq3000** [comment]
Thank you for the heads-up.

It seems the python module googletrans that we use to translate the ocr'ed text is not maintained anymore, see: https://github.com/ssut/py-googletrans/issues/280

To fix this issue, another module needs to be used or another translator needs to be implemented (such as DeepL, which offers a number of free translations monthly to test).

I unfortunately don't think I will have the time to fix this issue anytime soon, but PRs are welcome, or I will come back to it someday.

26 févr. 2023 17:53:12 kavikthewolfdog ***@***.***>:

**Comment by lrq3000** [comment]
Fixed in >= v0.6.0, will be published later. Thank you for your feedback.
