### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'display'

### ISSUE THREAD

**Issue by YogSottot** [lrq3000/pyugt#7]
When I press ctrl+shift+F3 I get this traceback.
kubuntu 22.04
Python 3.10.12

```
~/.local/bin/pyugt -c ~/.local/lib/python3.10/site-packages/pyugt/config.ini

pyugt - Python Universal Game Translator v1.0.6 - started
Languages available for OCR: []
Hit ctrl+shift+F3 to set the region to capture.
Hit ctrl+F3 to translate the region (make sure to close the translation window before requesting another one).
Hit ctrl+F2 to set AND translate a region.
Hit ctrl+p to show/hide OCR preview.
Press CTRL+C or close this window to quit.
selectRegion triggered
Exception in thread Thread-15 (process):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/lib/python3.10/site-packages/keyboard/_generic.py", line 58, in process
    if self.pre_process_event(event):
  File "/root/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 218, in pre_process_event
    callback(event)
  File "/root/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 649, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logically_pressed_keys) or (event_type == e.event_type and callback())
  File "/root/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 637, in <lambda>
    callback = lambda callback=callback: callback(*args)
  File "/root/.local/lib/python3.10/site-packages/pyugt/pyugt.py", line 237, in selectRegion
    sct_img = sct.grab(sct.monitors[int(config['USER']['monitor'])])
  File "/root/.local/lib/python3.10/site-packages/mss/base.py", line 118, in monitors
    self._monitors_impl()
  File "/root/.local/lib/python3.10/site-packages/mss/linux.py", line 385, in _monitors_impl
    display = self._handles.display
AttributeError: '_thread._local' object has no attribute 'display'
^CTraceback (most recent call last):
  File "/root/.local/bin/pyugt", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.10/site-packages/pyugt/pyugt.py", line 691, in main
    time.sleep(1)
```

I tried putting in the config: monitor = 0 / monitor = :0 / monitor = #0
```
echo $DISPLAY
:0
```

```
tesseract  --version
tesseract 5.3.2
 leptonica-1.82.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.1) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX512BW
 Found AVX512F
 Found AVX512VNNI
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.6.0 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8
 Found libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
```

**Comment by lrq3000** [comment]
I tested the app only on Windows. It seems there is a problem with managing displays in either the overlay I use (based on Tk) or the screenshot app (more likely). I will try to find a replacement, it shouldn't be too hard.

**Comment by lrq3000** [comment]
Sorry for the delay, I investigated a bit more the issue, and the module that is used to capture screenshots should be crossplatform. So I don't know why it is not finding the display on your system.

Could you please try to update the module maybe? Unfortunately pyugt is a bit old and so it is not yet packaged with the latest Python standards (ie, `pyproject.toml`), so you need to do that manually with:

`python -m pip install -U --user mss`

Could you please try and report if this improves the issue maybe?

**Comment by YogSottot** [comment]
> python -m pip install -U --user mss
It's already been updated

```Requirement already satisfied: mss in ./.local/lib/python3.10/site-packages (9.0.1)```

**Comment by lrq3000** [comment]
Thank you @YogSottot 

Can you please help me debug this further by trying to run the following in a Python prompt:

```
from mss import mss
with mss() as sct:
    sct.shot()
```

And if this doesn't work, can you please try the following:

```
from mss import mss
with mss() as sct:
    sct.shot(mon=-1, output='fullscreen.png')
```

**Comment by YogSottot** [comment]
> from mss import mss
> with mss() as sct:
>     sct.shot()

It worked, the screenshot file ```monitor-1.png``` was created

**Comment by lrq3000** [comment]
@YogSottot Thank you very much for your feedback! I think this issue is fixed in the dev release but another bug crept up due to modernizing the build to latest standards, I will fix this in the upcoming days and I'll let you know!

**Comment by lrq3000** [comment]
(The bug is that the config file is not included in the wheel anymore, I need to modify the build config)

**Comment by lrq3000** [comment]
@YogSottot Sorry for the delay, I have now updated `pyugt` (v1.0.9) on pypi, you should finally be able to run this version. If you have some time, could you please try it?

Note that the config.ini file resides in the module's folder, so it's a bit complicated to access it. I will fix this in a later release. Also note that you need to install Tesseract OCR v5, this also will be fixed in a future release. Thank you for your patience!

**Comment by YogSottot** [comment]
tesseract 5.3.2

```

./pyugt-venv/bin/pyugt -c pyugt-venv/lib64/python3.10/site-packages/pyugt/config.ini

pyugt - Python Universal Game Translator v1.0.9 - started
Languages available for OCR: []
Hit ctrl+shift+F3 to set the region to capture.
Hit ctrl+F3 to translate the region (make sure to close the translation window before requesting another one).
Hit ctrl+F2 to set AND translate a region.
Hit ctrl+p to show/hide OCR preview.
Press CTRL+C or close this window to quit.
selectRegion triggered
Exception in thread Thread-13 (process):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.local/lib/python3.10/site-packages/keyboard/_generic.py", line 58, in process
    if self.pre_process_event(event):
  File "/root/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 218, in pre_process_event
    callback(event)
  File "/root/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 649, in <lambda>
    handler = lambda e: (event_type == KEY_DOWN and e.event_type == KEY_UP and e.scan_code in _logically_pressed_keys) or (event_type == e.event_type and callback())
  File "/root/.local/lib/python3.10/site-packages/keyboard/__init__.py", line 637, in <lambda>
    callback = lambda callback=callback: callback(*args)
  File "/root/pyugt/pyugt-venv/lib/python3.10/site-packages/pyugt/pyugt.py", line 524, in selectAndTranslateRegion
    selectRegion(sct, RegionSelector, config, config_internal, quitOnSelect=True)
  File "/root/pyugt/pyugt-venv/lib/python3.10/site-packages/pyugt/pyugt.py", line 237, in selectRegion
    sct_img = sct.grab() if monitor < -1 else sct.grab(mon=monitor)  # sct.grab() captures the first monitor, sct.grab(mon=-1) captures all monitors, sct.grab(mon=0) captures monitor 0, etc.
TypeError: MSSBase.grab() missing 1 required positional argument: 'monitor'
```
monitor = -2 left by default

**Comment by lrq3000** [comment]
@YogSottot Sorry about that, I tripped up on some technicalities. I have updated again the app to v1.0.10, could you please try to `pip install --upgrade pyugt` once again?

I dropped attempts to auto detect which monitor to use, so it will use the first monitor by default, and if that's not the right one, you can change in the config file, hopefully this will work.

**Comment by YogSottot** [comment]
@lrq3000 
It's working now.
Thank you.
